version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - db
  front_end:
    container_name: front_end
    image: front_end
    ports:
      - "4200:4200"
    networks:
      - frontend
    depends_on:
      - back_end
  back_end:
    container_name: back_end
    image: back_end
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - db
networks:
  frontend:
    name: frontend
  backend:
    name: backend